ssh_config: ENC[AES256_GCM,data:2OQCfx1A4f5O9PV2TA0j/1TwFyf3mZNt3NmMXsQA4cEi+jHr4Dh5rM61khgQEMShKr0+cb6NQYzo3kwXYYKrteN2ODHY2/RZt2kJZ2OHo5WOJuH3LMx9TK9jGL2SYCUGkg==,iv:Bj/0o3cha/RdeH1L5lvQ9CXF6mKCz2KMYW6zioYbqG8=,tag:fhxqVM37ACAgFQDJX/Vbmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kzuj3nssduukunue5qk7hx7s7flvcedxqwncnz4swkw0kw0py5zq0rv928
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdUE3L2c4OEdISVVlZVJl
            dnJjWmdnYUU1bmNTeDlNS3cxODE5TEE2MXo4ClBCUlFPWjNwdWRONHY0QTJIYnRs
            YloxNTl1Z2tpSENnelU0V3J6QUtJeHMKLS0tIDVvUG5TTkFhb3YxU1Jjc1daZTFa
            SnBmWTQzQXdqOG9YY0JxWVYyOC8wa0kKOuFRRXG7qKWfrHMS5mM7ZxNKo3RNm0ZS
            lFrxM1B6Q1j0JZxfPYDkausGrIpuapmnp9PkuDhDwViuYNVds++/mA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age109z849eur4yny9m7fqgz9u3hjr7rkeeycknjkytj9nwwtnaqj5cssd7cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZmMvQUVDbXczekVPOTNh
            cmtkaHpXQWptQ0Q2ZytyU1RJZmRWQVpLNG5zClBnU1ZhQTVPS3BFY1JZdmE1bCtr
            RUV6VHZaMUZRZXNuVlFCM3Y1cTFkYmsKLS0tIDhEWndyVG5jYWkyeVVDdGVXTGZF
            WTdsaUxzRGdScGE2ZWdCTkc3TXpIeG8KzD5kalR5NudDH8vhszGDCVqQj6JRylsk
            llO3ubfxRtN3YvFPCpur5T9FvrnnSlaMbhA9X0MSvUrvdnwnlCDFYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-08T08:54:55Z"
    mac: ENC[AES256_GCM,data:l685RaNTUhLi0wqnunI5r0Ek25Z1uTk7CQSl6Ab6q1LuqQvQpiqoG/MFV6wwZKwHD2RCeevw36hEmD8cVTLZzCyKK/rln6xZYpfysX56c5qW7Ywjj5SONrtSu685LOYJV9km6z1axOerPeM3+14ZYSNwSbqgPWmACXwKs/5rRR8=,iv:ZLOcsNxtusflbPf0/Cr/Zu0MnSS+RdQs28aOygVCPpU=,tag:qqtZIGQnoG6xZQ+W70pSGA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
