ssh_config: ENC[AES256_GCM,data:erYZss/kWmTyi9Bv3jZ7gpXUkXZq5u2207kzKNAVadnC9aj1C4nD9kXIwIYrKGZixmLmO/XAIyVaz1btf0TDt23xMU3UfI1YZFvd7FmFXSp6rNp9JT1a/N9GoCwSHBO4MDMwPQ==,iv:O1uQSuJKeVXKdQC4KGXBiNxvLwBcQmFM0qOQ/pMXCJQ=,tag:qE1JK5M7+avoCbCSQUTJyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kzuj3nssduukunue5qk7hx7s7flvcedxqwncnz4swkw0kw0py5zq0rv928
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdUE3L2c4OEdISVVlZVJl
            dnJjWmdnYUU1bmNTeDlNS3cxODE5TEE2MXo4ClBCUlFPWjNwdWRONHY0QTJIYnRs
            YloxNTl1Z2tpSENnelU0V3J6QUtJeHMKLS0tIDVvUG5TTkFhb3YxU1Jjc1daZTFa
            SnBmWTQzQXdqOG9YY0JxWVYyOC8wa0kKOuFRRXG7qKWfrHMS5mM7ZxNKo3RNm0ZS
            lFrxM1B6Q1j0JZxfPYDkausGrIpuapmnp9PkuDhDwViuYNVds++/mA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age109z849eur4yny9m7fqgz9u3hjr7rkeeycknjkytj9nwwtnaqj5cssd7cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZmMvQUVDbXczekVPOTNh
            cmtkaHpXQWptQ0Q2ZytyU1RJZmRWQVpLNG5zClBnU1ZhQTVPS3BFY1JZdmE1bCtr
            RUV6VHZaMUZRZXNuVlFCM3Y1cTFkYmsKLS0tIDhEWndyVG5jYWkyeVVDdGVXTGZF
            WTdsaUxzRGdScGE2ZWdCTkc3TXpIeG8KzD5kalR5NudDH8vhszGDCVqQj6JRylsk
            llO3ubfxRtN3YvFPCpur5T9FvrnnSlaMbhA9X0MSvUrvdnwnlCDFYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-08T08:41:53Z"
    mac: ENC[AES256_GCM,data:Ei1ag55E3Ld8uIjxi8ZyAerOGlMG5Ap77dnPmZdby+liJ9iFYyr1UgBJGhdymx4piqu/l93Jb2XzGNO3s+QeMtyqHaJAf0CgBpSwbsJIdFuFAazJUzka0Yxa1zC7gdJVmXe5Mx7jr4t5lBJgHVY2OcpM6uQuuXqsqy3uD0OIj5g=,iv:+82FC/U60A2LqO5Gk9xBJIzr0ntZMPWON8biEGP6Rww=,tag:Ka9TY4DlasrdM+3uDwsEew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
