ssh_config: ENC[AES256_GCM,data:XBqLW2Z5VhpDiRNoudvlRp5P+FqOmeXAe8TnZaGXXb1S8yC95wfuGhzFPfyKeObwildd5Fko3ymB2kQpzn0qavf7czgJpXiDMN55+fPEUvnuP+3bP1YNCs9RBFgmxZBcHmDbSsVYlEZr9Xht/wjDS4yAVtTOfBzkU/6OWQJDKL4q8HOeuowsah0CFBtEsSMu1mkYqufvW+QEA9TTC2VqiNq51vOrZLA4MmJyaA==,iv:ZLZsEnb84Kdj3DQWwTLdbLrKVcoEYU8BkFWVPdzfbF8=,tag:saRe3eUNEz9iTLrinUb0ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kzuj3nssduukunue5qk7hx7s7flvcedxqwncnz4swkw0kw0py5zq0rv928
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdUE3L2c4OEdISVVlZVJl
            dnJjWmdnYUU1bmNTeDlNS3cxODE5TEE2MXo4ClBCUlFPWjNwdWRONHY0QTJIYnRs
            YloxNTl1Z2tpSENnelU0V3J6QUtJeHMKLS0tIDVvUG5TTkFhb3YxU1Jjc1daZTFa
            SnBmWTQzQXdqOG9YY0JxWVYyOC8wa0kKOuFRRXG7qKWfrHMS5mM7ZxNKo3RNm0ZS
            lFrxM1B6Q1j0JZxfPYDkausGrIpuapmnp9PkuDhDwViuYNVds++/mA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age109z849eur4yny9m7fqgz9u3hjr7rkeeycknjkytj9nwwtnaqj5cssd7cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZmMvQUVDbXczekVPOTNh
            cmtkaHpXQWptQ0Q2ZytyU1RJZmRWQVpLNG5zClBnU1ZhQTVPS3BFY1JZdmE1bCtr
            RUV6VHZaMUZRZXNuVlFCM3Y1cTFkYmsKLS0tIDhEWndyVG5jYWkyeVVDdGVXTGZF
            WTdsaUxzRGdScGE2ZWdCTkc3TXpIeG8KzD5kalR5NudDH8vhszGDCVqQj6JRylsk
            llO3ubfxRtN3YvFPCpur5T9FvrnnSlaMbhA9X0MSvUrvdnwnlCDFYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-09T07:57:35Z"
    mac: ENC[AES256_GCM,data:FPj/Ysgtlq2MOriMB3itUelqwvVn7MK2CvAeNuwn0udKXdGE/SEMEI5DJfhbLeyfvVkUWsIZBJrmxeiews0Io64J45VCYHc0nY/RIC9MwTQC32hf3t0Ik/OwfbMHa5LRn4JSPU33AXM091KPzHESEhxmo9m5aelOeUh+zJqVReM=,iv:ytinvMVggHcCBOp1Sk7+p7I4+gR7IPpD1qASBLxvWzo=,tag:PzDOYJj4ZWCe2dh5ErD3Ag==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
